"""baseline: схема, фактически работавшая до перехода на Alembic

Слепок схемы, которую создавал Base.metadata.create_all() вместе с ручными
ALTER'ами в init_db(). Отличий от модели на момент создания нет (проверено
alembic.autogenerate.compare_metadata), поэтому существующие установки
переводятся на эту ревизию через `alembic stamp` без пересоздания таблиц.

Улучшения схемы (уникальные ключи, ON DELETE) идут отдельной ревизией — так
они применяются и к новым, и к уже существующим базам.

Revision ID: 9d180a1255ac
Revises:
Create Date: 2026-08-06 20:21:43.560908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d180a1255ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('airport_localities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('measure', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('trunk', 'local', 'interregional', 'subsidir', name='routetype'), nullable=False),
    sa.Column('regularity', sa.Enum('regular', 'irregular', 'non_commercial', name='shippingregularity'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('position', sa.Enum('admin', 'guest', 'employee', name='userposition'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('locality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locality_id'], ['airport_localities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('shipping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('airlineInd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('shipping_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Enum('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', name='months'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['shipping_id'], ['shipping.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('airportInd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Enum('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', name='months'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airportInd')
    op.drop_table('airlineInd')
    op.drop_table('shipping')
    op.drop_table('airports')
    op.drop_table('users')
    op.drop_table('routes')
    op.drop_table('indicators')
    op.drop_table('airport_localities')
    op.drop_table('airlines')
    # ### end Alembic commands ###
