"""entities

Revision ID: e676ba239c69
Revises: 7f5a0bf5d509
Create Date: 2026-03-17 15:19:45.707135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e676ba239c69'
down_revision: Union[str, Sequence[str], None] = '7f5a0bf5d509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('trunk', 'local', 'interregional', 'subsidir', name='routetype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('trunk', 'local', 'interregional', 'subsidir', name='routetype'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###
